### PR TITLE
Add free-standing function to concatenate datasets

### PR DESCRIPTION
**Pull request by tglarner**
This branch adds a free-standing function to create a new datset as the concatenation of others. That way the usage of the instance method Dataset as a class method is sidestepped and user code becomes less confusing.

### CODE REVIEW

**Comment by boeddeker** [comment]
What do you think about the special case, that the input to concatenate is only one dataset?
To reduce the iteration overhead, there could be a short path:
```python
if len(datasets) == 1:
    return datasets[0]
```

**Comment by tglarner** [comment]
Good point. Furthermore, this increases symmetry ith the member function. Short circuiting is implemented with commit

**Comment by jheymann85** [comment]
Maybe datasets should be a list so behavior is the same as in numpy, tf, pytorch etc.

**Comment by tglarner** [comment]
We could do that, but I tried to stay as close as possible to the corresponding member function. If we would change this here, we should change it in the member function as well. However, that would be a breaking change and would thus need another pull request.

**Comment by boeddeker** [comment]
Good point with the compatibility. We should try to support code that is valid in other software. 
How about to support both?

**Comment by tglarner** [comment]
I have no objections to the suggestion, but I suggest that we merge this pull request and open a separate issue which we can adress with another pull request in the near future.

**Comment by boeddeker** [comment]
You are right. This PR is fine. I will merge it.

**Pull request merged**
